# Generated by Django 3.0.5 on 2020-06-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='imageId',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
