# Generated by Django 3.0.5 on 2020-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200604_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
